# Copyright (c) nftables-json Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

unstable_features = true

binop_separator = "Back"
comment_width = 100
edition = "2021"
max_width = 120
use_small_heuristics = "Max"
wrap_comments = true
